### ISSUE TITLE
Command make on wsl error

### ISSUE THREAD

**Issue by Achild29** [hiveeyes/terkin-datalogger#53]
![FC58DE4A-6DFB-4049-A17B-98871CA48469](https://user-images.githubusercontent.com/60103780/72735741-05374a00-3bcf-11ea-9c2d-665b70673fc2.jpeg)
When I type make on terminal (wsl) it show an error
It show like this

**Comment by thiasB** [comment]
How is your error related to this repository?

**Comment by thiasB** [comment]
not related
