### ISSUE TITLE
broken link in documentation 

### ISSUE THREAD

**Issue by ClemensGruber** [hiveeyes/terkin-datalogger#54]
On https://github.com/hiveeyes/terkin-datalogger/blob/master/doc/sandbox-setup.rst is a link in the last paragraph to 

getting started with Pycom MicroPython
https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/master/doc/pycom-getting-started.rst

This link is broken (404)

**Comment by amotl** [comment]
Thanks for reporting and fixing!
