### ISSUE TITLE
Add support for DS3231 RTC

### ISSUE THREAD

**Issue by amotl** [hiveeyes/terkin-datalogger#68]
@poesel is looking into integrating support for the DS3231 RTC, see also [1]. We already included the corresponding lowlevel driver into the sandbox environment through 77d788ec.

[1] https://community.hiveeyes.org/t/treiberunterstutzung-fur-die-ds3231-rtc/3053

**Comment by poesel** [comment]
Support added with https://github.com/hiveeyes/terkin-datalogger/tree/c4e8a05c9b049d54667d0f47a355c81543e93748
