### ISSUE TITLE
sandbox / add upload-settings to make help

### ISSUE THREAD

**Issue by ClemensGruber** [hiveeyes/terkin-datalogger#78]
The output of `make help` is automatically created from the comments in the https://github.com/hiveeyes/terkin-datalogger/blob/master/Makefile but there are more helpful commands like `make upload-settings ` definde in https://github.com/hiveeyes/terkin-datalogger/blob/master/tools/micropython.mk

How can I add some of this commands to show up in `make help`?

**Comment by amotl** [comment]
This has been included within 8b014420 already. Thanks again!

**Comment by ClemensGruber** [comment]
Nice! So my confusion is also addressable, ;-) I had a look in the repo and wondered why the comment did not show up in my shell, not recoginzing that you worked already on that! Thx!
